### ISSUE TITLE
[Belo Horizonte/MG] Riderman de Sousa Barbosa

### ISSUE THREAD

**Issue by Ridermansb** [frontendbr/me-contrata#100]
## Nome completo

Riderman de Sousa Barbosa

## Localidade

Belo Horizonte, MG

## Apresentação

Criativo, entusiasta e estudante na maior parte do tempo. No restante escrevo código especialmente em Javascript. Autentico, pró-ativo, apaixonado pelo trabalho, especialista em tecnologias front-end e algum conhecimento em back-end.

## Especialidades

 - React, React Patterns
 - Mobx / Redux
 - Jest, Karma, Chai
 - Express
 - MongoDB

## Nível

- [ ] Estágio
- [ ] Júnior
- [ ] Pleno
- [x] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

 - https://www.linkedin.com/in/ridermansb/

## Site

 - https://github.com/ridermansb
 - https://gitlab.com/ridermansb
 - https://stackoverflow.com/users/491181/ridermansb
 - https://twitter.com/ridermansb

**Comment by pablolopesk8** [comment]
Olá Riderman, estamos com uma vaga na Zotto Soluções Mobile para Desenvolvedor Frontend.
Você tem interesse? Pode nos enviar seu currículo por email com seus dados de contato (nome, telefone e email)?

**Comment by Ridermansb** [comment]
Ola @pablolopesk8, agradeço pela oportunidade, mas no momento não tenho interesse.
Desculpe, esqueci de atualizar essa issue.
