### ISSUE TITLE
[Guarulhos/SP] Paulo José Carneiro Pires

### ISSUE THREAD

**Issue by paulo36** [frontendbr/me-contrata#102]

**Comment by renanlara** [comment]
@LFeh, não sei mais como ajudar ele :(

**Comment by alinebastos** [comment]
@paulo36 te recomendo assistir este curso de Git e GitHub para iniciantes, é bem importante saber essas ferramentas pro nosso trabalho :)
https://www.udemy.com/git-e-github-para-iniciantes/

**Comment by paulo36** [comment]
ok.pode apagar o issue? Vou procurar no youtube algo.

**Comment by alinebastos** [comment]
Mas eu acabei de te passar um link de um curso bom e gratuito.
