### ISSUE TITLE
[Blumenau/SC] Gabriel Dias Bahniuk

### ISSUE THREAD

**Issue by gabrielbahniuk** [frontendbr/me-contrata#111]
## Nome completo

 Gabriel Dias Bahniuk.

## Localidade

Blumenau / Santa Catarina

## Apresentação

Gabriel Dias Bahniuk, 22 anos, solteiro, nascido e residente na cidade de Blumenau - SC.
Autodidata, sempre buscando aprender novas tecnologias e aperfeiçoar os conhecimentos já existentes, aplicando na prática o que aprende da melhor forma possível.

Trabalhando numa multinacional alemã desde 2015 no desenvolvimento (tanto front como back-end) de aplicativos para automatização de processos internos e de clientes na Alemanha.

## Outras Informações

Disponibilidade de horário e viagens, inclusive mudança, dependendo da proposta.

## Especialidades

- HTML5
- CSS3
- JavaScript
- jQuery
- PHP
- Java
- Oracle
- MySQL
- PL/SQL
- Linux
- Git

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/gabriel-dias-bahniuk/

## Site

https://github.com/gabrielbahniuk

**Comment by POLLEZI** [comment]
Bom dia! Td joia?
Vc avalia oportunidades em SP?

## Descrição da vaga
_ React
- Desenvolvimento de interfaces
- Experiência em recorte de layouts com Photoshop / InVision
- Javascript - Vanilla e jQuery
- HTML / HTML5 
- CSS3 - SASS / SCSS 
- Consumo de APIs REST
- Git


## Tipo de contratação
CLT

## Local :
Alphaville – SP

## Benefícios
VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Como aplicar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
- enviar no assunto: Vaga REACT front-end

**Comment by gabrielbahniuk** [comment]
> Bom dia! Td joia?
> Vc avalia oportunidades em SP?
> 
> ## Descrição da vaga
> _ React
> 
> * Desenvolvimento de interfaces
> * Experiência em recorte de layouts com Photoshop / InVision
> * Javascript - Vanilla e jQuery
> * HTML / HTML5
> * CSS3 - SASS / SCSS
> * Consumo de APIs REST
> * Git
> 
> ## Tipo de contratação
> CLT
> 
> ## Local :
> Alphaville – SP
> 
> ## Benefícios
> VR
> VT
> Convenio Médico
> Convenio Odontologico
> Auxilio Creche
> Convenio Farmácia
> Seguro de Vida
> 
> ## Como aplicar
> Por favor envie um cv para [adriana.pereira@resourceit.com](mailto:adriana.pereira@resourceit.com) ou indique um amigo!!!
> 
> * enviar no assunto: Vaga REACT front-end

Olá, 
no momento estou fora do país, pretendo ficar mais um tempo por aqui ainda, mas obrigado pelo contato.
Vou editar o perfil, e caso encontre alguem eu indico sim.
Obrigado!
