### ISSUE TITLE
[São Paulo/SP] Jonatas Antunes de Souza

### ISSUE THREAD

**Issue by jsouza23** [frontendbr/me-contrata#114]
## Nome completo

Jonatas Antunes de Souza

## Localidade

São Paulo/SP

## Apresentação

Olá! Meu nome é Jonatas tenho 25 anos, sou um desenvolvedor web com foco em front-end. 

Migrei recentemente da área de publicidade para a área de tecnologia onde adquiri experiência em desenvolvimento de sites com Wordpress, criação de campanhas de e-mail marketing e Google Adwords. Busco oportunidades para trabalhar em equipes de desenvolvimento com objetivo de me desenvolver e atuar em projetos colaborativos.

Costumo participar de palestras, meetups e cursos sempre que posso para aumentar meu aprendizado e tenho como próximos objetivos alavancar meu workflow com frameworks de JavaScript, ferramentas de DevOps e hospedagem na nuvem.

## Outras Informações

Possuo fácil acesso a maioria das regiões de SP capital, disponibilidade total de horário.

## Especialidades

- HTML
- CSS
- JavaScript
- Wordpress
- PHP
- MySql
- Node.js

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/jonatasantunes/ 

## Site

http://jonatasdev.com.br/

**Comment by jsouza23** [comment]
Fechando a issue pois consegui uma vaga de front end (através de outro site).

**Comment by LFeh** [comment]
Parabens mano!
