### ISSUE TITLE
[São Paulo/SP] Daniela Duarte

### ISSUE THREAD

**Issue by danieladuarteng** [frontendbr/me-contrata#116]
## Nome completo

Daniela Duarte dos Santos

## Localidade

São Paulo/SP

## Apresentação

Desenvolvedora Front-End, Técnica em Informática e Engenheira da Computação.

Apaixonada por tecnologia e empreendedorismo, apoia o desenvolvimento de mais mulheres na área de tecnologia, por isso escreve no seu blog (www.danieladuarte.com.br) sobre tecnologia, experiências e aprendizados, a fim de inspirar e orientar cada vez mais, mulheres que estão ou querem entrar no mundo da computação.

Possui experiência nas áreas de tecnologia, administração e marketing desde startups à multinacionais como Santa Marina, CBB Web (Medcel), Saint-Gobain e Kestraa.

Teve seu TCC (Cartão Virtual Biométrico) patenteado e selecionado para o programa de mentoria de startups da Escola de Negócios do Sebrae.

Selecionada entre 1500 inscrições para ser uma das 100 mulheres empreendedoras a participar do programa de liderança feminina da Google o Womenwill.

## Outras Informações

Tenho preferência por oportunidades 100% remotas, mas avalio propostas alocada também.

Educação:

UDACITY Brasil
Nanodegree Desenvolvedor React
2018-2019

UNIBTA - Centro Universitário
Bacharel em Engenharia da Computação
2013-2017

ETEC Jaraguá
Técnico em informático com ênfase em programação
2012-2013

Codecademy
Learn HTML & CSS
2017

Codecademy
Learn Responsive Design
2017

TIEXAMES
Fundamentos em Gerenciamento de Serviços de TI com base na ITIL Foundation (V3 - ed. 2011)
2015

## Especialidades

- HTML/HTML5
- CSS/CSS3/ Material UI, Stylus e CSS in JS 
- ReactJs / React-Redux 
- Formik
- Testes unitários: Jest e Enzyme
- Design Responsivo
- Usabilidade
- Mobile First
- JavaScript
- Git/GitHub
- Amazon EC2
- HTTP
- Adobe Illustrator
- Google Analytics
- SEO
- SCRUM

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [X] CLT
- [x] Freela

## Tipo de trabalho

- [X] Remoto - Parcial
- [x] Remoto - Total
- [X] Alocado

## Contato

https://www.linkedin.com/in/danieladuarteng

## Site

http://danieladuarte.com.br/

**Comment by jbaladao** [comment]
Bom dia Daniela,

Você teria interesse em participar do processo de seleção para dev. front-end no SuperAgendador.com?

Caso sim, por favor, encaminhe um e-mail para jbaladao (at) superagendador.com

Abs.
Juliano

**Comment by LuanaDaud** [comment]
Ola Daniela,

Sou coordenadora de talentos da zx ventures, uma área de inovação e tecnologia dentro da ambev. Gostaria de bater um papo com você, topa? Pode me passar seu fone?

**Comment by danieladuarteng** [comment]
> Ola Daniela,
> 
> Sou coordenadora de talentos da zx ventures, uma área de inovação e tecnologia dentro da ambev. Gostaria de bater um papo com você, topa? Pode me passar seu fone?

11994597735

**Comment by sistemaweb** [comment]
Boa tarde, veja se interessa: https://github.com/frontendbr/vagas/issues/1639
