### ISSUE TITLE
[São Paulo/SP] Lucas Draichi

### ISSUE THREAD

**Issue by Draichi** [frontendbr/me-contrata#139]
## Nome completo

Lucas Draichi

## Localidade

São Paulo/SP

## Apresentação

Estudei engenharia da computação na UNIP e depois mudei para UNICSUL, já prestei serviços à IBM Brasil, Tagview, 2Mundos. Posso trabalhar com qualquer linguagem, front ou back-end, mais experiências estão no meu [site](https://draichi.github.io/portfolio/index.html).

Projeto pessoal em live:

- Link: https://bud-fox.github.io/live/
- Código: https://github.com/Bud-Fox

## Outras Informações

Disponível à viagens, disponível à receber pagamento em Bitcoin.

## Especialidades

- Python
- JavaScript (Vanilla)
- Vue.js / Nutx.js
- PWA
- Cryptocurrencys
- HTML
- CSS
- PHP
- Ruby on Rails
- MySQL
- Webpack / Gulp
- Yarn / NPM

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Site

https://draichi.github.io/portfolio/index.html

**Comment by Paulogrupe** [comment]
Olá Lucas

Estou com uma vaga de front-end.
Se interessar envie seu curriculum para pg@individuals.io

abs

Paulo
