### ISSUE TITLE
[Belo Horizonte/MG] Rafael Godoy

### ISSUE THREAD

**Issue by Rarfael** [frontendbr/me-contrata#144]
## Nome completo

Rafael Lopes Silva de Godoy

## Localidade

Nova Lima / MG

## Apresentação

Trabalho profissionalmente com desenvolvimento WEB desde 2017, atuei principalmente no desenvolvimento de APIs utilizando PHP com Laravel 5.5 e front end com stack web padrão (HTML, CSS e JavaScript/jQuery), ao longo do meu trabalho passe a implementar o framework Vuejs. Atualmente tenho focado meus esforços no desenvolvimento front end, principalmente JavaScript. Tenho experiência com Vuejs e atualmente priorizo o aprimoramento de minhas habilidades com React.

## Outras Informações

Moro em Nova Lima, mas procuro algo em Belo Horizonte, pois é onde passo maior parte do tempo. Tenho flexibilidade de horário.

## Especialidades

- JavaScript (Vuejs)
- HTML
- CSS (Bootstrap, materializecss)
- PHP
- MySQL
- Git
## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/rafael-ls-godoy/

**Comment by leomp12** [comment]
Fala @Rarfael , o issue é antigo, como está sua situação agora? Segue aberto a um desafio novo com este stack?

**Comment by Rarfael** [comment]
> Fala @Rarfael , tudo bem?
> O issue é antigo, como está sua situação agora? Segue aberto a um desafio novo com este stack?

Ola @leomp12, tudo bem sim!

Essa issue é bem antiga mesmo e minhas informações já estão todas desatualizadas rs. 
No momento estou empregado e não tenho interesse, mas obrigado pelo contato.
Abraço.
