### ISSUE TITLE
SAO PAULO - FRONTEND - RESOURCE

### ISSUE THREAD

**Issue by POLLEZI** [frontendbr/me-contrata#148]
## Empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países. 
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Descrição da vaga
- Desenvolvimento de interfaces
- Experiência em recorte de layouts com Photoshop / InVision
- Javascript - Vanilla e jQuery
- HTML / HTML5 
- CSS3 - SASS / SCSS 
- Consumo de APIs REST
- Git

## Tipo de contratação
CLT

## Local :
Alphaville – SP
Interlagos - SP

## Benefícios
VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Como aplicar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
- enviar no assunto: Vaga front-end

**Comment by LFeh** [comment]
Aqui é para candidatos se anunciarem, vagas apenas no [vagas](https://github.com/frontendbr/vagas)
