### ISSUE TITLE
[São Paulo/SP] Victor Antonio

### ISSUE THREAD

**Issue by MrS4w** [frontendbr/me-contrata#150]
## Nome completo

Victor Antonio Barbosa Silva

## Localidade

São Paulo / SP

## Apresentação

Me formei em Análise e Desenvolvimento de Sistemas em julho de 2018 e gosto muito de atuar como desenvolvedor tanto back-end quanto front-end, ainda não me prendi a uma área em específico, tive oportunidade de trabalhar durante 3 meses com HTML, CSS e Java Web (JSP e Servlet).
Fácil aprendizagem e disposição para novos conhecimentos.

## Outras Informações

Disponibilidade para início imediato e para cidades como Salto, Itu ou Indaiatuba.

## Especialidades

- JavaScript - Básico
- ES6 - Básico
- HTML - Intermediário
- CSS - Intermediário
- Bootstrap - Básico/Intermediário
- PHP - Básico
- Python - Básico
- Django - Básico
- Java EE (JSP, Servlet) - Básico/Intermediário
- Java EE (JSF e PrimeFaces) - Básico
- Java para Android - Básico
- SQL Server / MySQL - Básico
- Git - Intermediário
- Inglês - Intermediário/Avançado

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

 https://linkedin.com/in/victor-antonio-5b83b514a

**Comment by MrS4w** [comment]
@LFeh é Júnior

**Comment by LFeh** [comment]
My bad

**Comment by sistemaweb** [comment]
Boa tarde, veja se interessa: https://github.com/frontendbr/vagas/issues/1639
