### ISSUE TITLE
[Porto Alegre/RS] Aline Bastos

### ISSUE THREAD

**Issue by alinebastos** [frontendbr/me-contrata#16]
## Nome completo

Aline Bastos

## Localidade

Porto Alegre/RS

## Apresentação

Estudante de Computer Science na [UoPeople](https://www.uopeople.edu/), trabalho como desenvolvedora Frontend há 8 anos. Trabalhei muito tempo focando em CSS e jQuery, mas agora estou procurando oportunidades para trabalhar com Javascript puro e outros frameworks, além de testes. Tenho também boas noções de linguagens de backend.

Atuo bastante na comunidade como mentora e escritora e, em breve, como palestrante.

Procuro por oportunidade remota com flexibilidade de horário.

## Outras Informações

Procuro home-office com flexibilidade de horário.

## Especialidades

- JavaScript
- HTML
- CSS
- Frameworks CSS (Sass, Bootstrap, Foundation, Less)
- Ajax
- Git/GitHub
- Webpack
- jQuery

## Estudando

- React
- Testes

## Nível

- [ ] Júnior
- [x] Pleno
- [x] Sênior

## Tipo de contratação

- [ ] Estágio
- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/alinebastos/

**Comment by DRS90** [comment]
A Aline é uma profissional de extrema competência e uma pessoa maravilhosa, agrega qualquer time, sempre proativa e disposta a ajudar.

**Comment by alinebastos** [comment]
Estou empregada ❤️
