### ISSUE TITLE
[Sul / Sudeste] Alexsandro Godoy Wolff

### ISSUE THREAD

**Issue by alexgwolff** [frontendbr/me-contrata#174]
## Nome completo

Alexsandro Godoy Wolff

## Localidade

Blumenau - SC - Atual

## Apresentação

Sou desenvolvedor fullstack mas estou a procura de vaga para frontend.
Tenho experiência com React, Redux e Redux Sagas e também tenho forte experiência em Web Components (W3C Spec).
Tenho forte interesse por construção de frameworks de componentes web sendo em React ou nativo com Web Components. Sou apaixonado por tecnologias emergentes e tenho como hobbie ler e testar as publicações rascunhos da W3C. 
Estou buscando um desafio fora da minha cidade, estou aberto a vagas em Curitiba, Campinas, Floripa, Joinville ou até em outra cidades não citadas. 
Tenho interesse maior em empresas de produtos principalmente ERP Web e Ferramentas de BI.
Vagas em P&D estão muito no meu radar.

## Outras Informações
Atualmente estou empregado e quero mesmo é um desafio. Quero me focar em um produto/segmento e me tornar especialista na área. Abaixo alguns projetos que já trabalhei tanto com frontend como backend... 

🛠 Projetos 
- Framework baseado em HTML (Web Componentes - W3C Spec ) para construção de relatórios de Business Intelligence sem programação.
- Engines DSL baseados em Javascript (ChakraCore) para construção dinâmicas de dataset usando Javascript. ( node.js 'like' engines)
- Engine de ELT baseado na linguagem do PowerBI porém em Javascript.
- Fabrica de Software; web apps em geral baseados em React.js e Vue.js
- Web APP para visualização de relatórios de Business Intelligence com React

## Especialidades

- JavaScript
- HTML
- CSS
- Web Components (W3C Spec)
- React
- Redux e Redux Sagas

## Nível

- [ ] Estágio
- [ ] Júnior
- [ ] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Cooperado
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/alex-godoy-wolff-54b677106/

**Comment by Renatadt** [comment]
Alex, te chamei no IN! Abs
