### ISSUE TITLE
[Apucarana/PR] Matheus Mazeto

### ISSUE THREAD

**Issue by matheusmazeto** [frontendbr/me-contrata#197]
## Nome completo

Matheus Mazeto

## Localidade

Apucarana - Paraná

## Apresentação

Eu sou um Cientista da Computação apaixonado pelo
desenvolvimento Web, especialmente pelo Front-end.
Eu sempre anseio por novos desafios e tento aperfeiçoar
minhas habilidades em novas tecnologias.
Sou um profissional dedicado que procura melhorar sempre.
Interesses: Web e Mobile.

## Outras Informações

Estou em constante evolução, sempre aperfeiçoando conhecimento através de diversos cursos/estudos, me mantendo atualizada com as tecnologias utilizadas no mercado e participo de palestras, meetups e eventos sempre que possível.

## Especialidades
- HTML
- CSS
- Sass / Scss
- Design Resposivo
- JavaScript (Vanilla & ES6)
- ReactJS
- Api Restful
- Boas práticas de projeto

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/matheus-mazeto-94076680/

## Site

https://matheusmazeto.github.io/

**Comment by ledbruno** [comment]
Fala Matheus, tudo certo?

Trabalho em um time de inovação e tecnologia na Senior Sistemas em Blumenau/SC. Temos diversas oportunidades para desenvolvimento de software back/front/full-stack e data engineer.
 
Nossa equipe é responsável por projetos inovadores na área de IA/Chatbots, mobile, engines de workflow entre outros.
 
Gostaria de saber mais a respeito? Ficaremos muito gratos em trocar uma ideia e saber mais do seu momento profissional.

**Comment by felipefialho** [comment]
Olhai @matheusmazeto :)
