### ISSUE TITLE
[Itapevi/SP] Paulo Edson Matos Xavier

### ISSUE THREAD

**Issue by developer-sp** [frontendbr/me-contrata#199]
## Nome completo

Paulo Edson Matos Xavier.

## Localidade

Itapevi - SP

## Apresentação

Técnico de informática para Internet, cursando Análise e Desenvolvimento de Sistema, autodidata interessado em aprender coisas novas e da atualidade, apaixonado por linux e tecnologia.

## Outras Informações

Disponibilidade para Grande São Paulo e para eventuais viagens.

## Especialidades

- HTML5
- CSS3(BEM, SASS)
- JavaScript(ES6+, JQuery, VueJs)
- GIT, GIT FLOW, GITHUB
- Gerenciadores de pacote(NPM e Yarn)
- WEBPACK
- GULP
- PWA
- Inglês Técnico

## Nível

- [ ] Estágio
- [x] Júnior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Total
- [ ] Alocado
- [x] CLT
- [x] PJ

## Contato

https://www.linkedin.com/in/paulomatos-sp/

**Comment by rodneyamancio** [comment]
Boa tarde.
Nós temos uma vaga para atuar dentro do ecossistema SAP e Google Cloud Plataform.
A Vaga não exige experiência e na verdade é para aprender essas tecnologias.

Se tiver interesse por favor entrar em contato com o CV e pretensão salarial no modelo PJ para recrutamento.br@grupointelsis.com 
Obrigado.

**Comment by michelleasouza** [comment]
Olá Paulo, bom dia!

Estou com uma vaga de Desenvolvedor Fullstack para trabalhar em uma Fintech localizada em Alphaville. Tentei entrar no seu perfil do Linkedin, mas ele está indisponível.
Se ainda estiver a procura de oportunidade, envie seu cv + pretensão salarial para michelle.a@mendestalent.com.br

Obrigada.

**Comment by developer-sp** [comment]
Bom dia Michele, estou envolvido em um projeto, todavia agradeço o convite e a informação que meu linkedin está indisponível.
