### ISSUE TITLE
[Bauru/SP] Willian Gomes de Oliveira

### ISSUE THREAD

**Issue by willoliveira** [frontendbr/me-contrata#241]
## Nome completo

Willian Gomes de Oliveira

## Localidade

Bauru/SP

## Apresentação

Desenvolvedor com quase 10 anos de experiência, focado na área de front-end, sempre com mindset ágil, atuando tmabém como lider técnico dentro do contexto de vários times multidisciplinares. 

## Outras Informações

Preferência por trabalho remoto

## Especialidades

- JavaScript
- HTML
- CSS
- React/redux
- Angular 2+
- Git

## Nível

- [ ] Estágio
- [ ] Júnior
- [ ] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/willian-gomes-de-oliveira-1a5712177/

## Site

https://github.com/willoliveira

**Comment by marcelodl** [comment]
Fala Willian, tudo bem? Me chamo Marcelo, sou GP de um grupo empresarial do Nordeste. Estou com uma vaga para dev parcial, tens interesse? Tiver interesse manda um e-mail pra mim em marcelo@acessetecnologia.com.br. Abraço
