### ISSUE TITLE
[Itapema/SC] Diego Mais

### ISSUE THREAD

**Issue by diegomais** [frontendbr/me-contrata#269]
## Nome completo

Diego Mais

## Localidade

Itapema / SC

## Apresentação

**5+ anos de experiência em desenvolvimento de software (principalmente JavaScript)**. Possuo diversos projetos no GitHub que desenvolvo por conta própria e que demonstram minhas habilidades. Atualmente interessado em **Angular**, **ReactJS**, **React Native** e **Node.js**. *Busco oportunidade para atuar como desenvolvedor front-end ou full-stack*.

**Profissional preparado para desenvolver aplicações de ponta com as mais modernas tecnologias do mercado e comprometido em atingir os objetivos propostos**. Gostaria de encontrar um ambiente onde possa aplicar os conhecimentos que possuo da melhor forma para entregar valor, bem como para me desenvolver, tanto profissionalmente como pessoalmente. *Vamos construir algo incrível juntos!*

Sou bacharel em **Sistemas de Informação**, tendo concluído o curso em 2009. Recentemente conclui o **React Nanodegree** da Udacity em março de 2019. Além destes, completei a jornada da 7ª turma do **Bootcamp GoStack** da RocketSeat nas tecnologias NodeJS, ReactJS e React Native com aproveitamento *9,9* em agosto de 2019.
Sou **fluente em inglês**, tendo pontuação *885* no TOEIC em 2019.

## Outras Informações

- 40h semanais disponíveis.
- Procuro por trabalho remoto ou presencial
- Considero possibilidade de mudança.
- Disponibilidade para viagens, cursos e palestras.

## Especialidades

- JavaScript: Node.js, Express, ReactJS (Hooks), React Native, Redux, Angular2+, TypeScript, npm, Yarn, etc
- HTML5
- CSS3: SCSS e Bootstrap
- SQL: PostgreSQL e MySQL
- NoSQL: MongoDB, Redis e Firebase
- Git: GitHub

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/diegomais

## Site

https://github.com/diegomais
https://diegomais.github.io

**Comment by sergiofm** [comment]
Olá Diego, tudo bem?
Estamos com uma vaga aberta na Mettzer, 100% remoto. 
Se tiver interesse, aqui nesse link tem mais detalhes: https://github.com/frontendbr/vagas/issues/3183

Um abraço!
