### ISSUE TITLE
[Guarulhos - SP] Aline Dias Melo

### ISSUE THREAD

**Issue by alinedmelo** [frontendbr/me-contrata#29]
## Nome completo

Aline Dias Melo

## Localidade

Guarulhos - SP

## Apresentação

Me formei em Sistemas para Internet em Julho de 2016 e trabalho atualmente como desenvolvedora front end júnior utilizando no dia a dia em html5, Css/Sass, Javascript, Design responsivo, Git.

Gosto de trabalhar em equipe, adquirir e compartilhar conhecimento e procuro trabalhar em empresas e  projetos que permitam o aprendizado de novas tecnologias. Sempre que posso compareço aos eventos da comunidade, principalmente os Meetups.

## Especialidades

- HTML
- CSS / SASS
- JavaScript
- Git
- Gulp

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/alinediasmelo

## Site

https://alinedias.net

**Comment by carloshenriqueribeiro** [comment]
Aline, tudo bem ? Gostamos muito do seu perfil e queremos + mulheres no nosso time (já temos algumas).
Tente concluir o nosso desafio
https://github.com/devpartner-br/frontend-test
