### ISSUE TITLE
[Duque de Caxias/RJ] Jonathan da Silva Pauluze

### ISSUE THREAD

**Issue by jonathanpauluze** [frontendbr/me-contrata#293]
## Nome completo

Jonathan da Silva Pauluze.

## Localidade

Duque de Caxias / RJ. 

## Apresentação

Apaixonado por desenvolvimento web e mobile, curto o processo de aprendizagem da teoria à prática e adoro novos desafios. Amo dividir conhecimento e trabalhar em equipe. Sou dinâmico, comprometido, pró-ativo, muito dedicado e adepto a mudanças. Trabalhei com VueJS e Vuetify num projeto Open Source chamado [New School](https://newschoolapp.com.br). A New School é uma startup social que busca levar educação de qualidade traduzida em uma linguagem jovial para as periferias do Brasil.

## Outras Informações

Possuo disponibilidade para qualquer horário.

## Especialidades

- HTML
- CSS
- SASS/Scss
- JavaScript
- VueJS

## Nível

- [x] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/jonathanpauluze

**Comment by felipeuntill** [comment]
Ainda está procurando oportunidades?

**Comment by jonathanpauluze** [comment]
@felipeuntill Eu fui contratado recentemente e esqueci de atualizar aqui, mas se for pra algum freelancer você pode me contatar que eu estou aceitando sim. Obrigado por responder. :)
