### ISSUE TITLE
[Porto Alegre/RS] Ricardo Gosch

### ISSUE THREAD

**Issue by rgosch** [frontendbr/me-contrata#3]
## Nome completo

Ricardo Gosch

## Localidade

Rio Grande do Sul - Brasil

## Apresentação

Sou estudante autodidata, trabalho como Desenvolvedor Front-end em uma grande empresa de Porto Alegre. Procuro novos desafios, novas oportunidades!

Tenho um ótimo conhecimento em JavaScript, CSS e HTML. O que abre um grande leque de possibilidades práticas.

## Outras Informações

Disponibilidade para mudanças. O horário é indiferente.

### JavaScript/Node
- Ecmascript 2015 (ES6)
- VueJS
- jQuery
- Highcharts
- Gulp

### CSS
- Pré-processador SASS
- Pré-processador Stylus
- Pré-processador LESS
- CSS3
- Bootstrap
- Layout Responsivo (mobile first)

### HTML
- Acessibilidade Web

## Nível

- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/ricardogosch

**Comment by fdaciuk** [comment]
@rgosch, por favor, depois só atualize o título da issue com sua cidade e estado:

```
[Porto Alegre/RS] Ricardo Gosch
```

Valeu =)

**Comment by rgosch** [comment]
Consegui a oportunidade que procurava. Infelizmente não foi através deste repositório, mas certamente ele tem um enorme poder! Core, tem meu apoio no que for necessário.

**Comment by fdaciuk** [comment]
Legal @rgosch! Sucesso pra ti \o/
