### ISSUE TITLE
[Guarulhos /SP] Douglas Julião

### ISSUE THREAD

**Issue by dougjuliao** [frontendbr/me-contrata#30]
## Nome completo

Douglas Julião Marques

## Localidade

Guarulhos São Paulo

## Apresentação

Me formei em Sistemas de Informação em 2014 e atuo na área do Desenvolvimento desde 2012, gosto bastante de criar páginas em html e estilizar em css, sempre estou brincando fazendo algum projeto pessoal, tento sempre me manter atualizado e conhecer pelo menos um pouco das tecnologias que vão aparecendo, sou focado nas demandas que me são passadas e trabalho muito bem em equipe e com prazos, tenho uma afinidade por design pois no tempo de estágio eu trabalhei com design e desenvolvimento(Front e Back), procuro ser um bom desenvolvedor Front End e participar de projetos inovadores e divertidos de criar, gosto muito de aprender cada dia mais e de resolver os problemas que aparecem no dia a dia.

## Especialidades

- JavaScript
- HTML
- CSS / SASS
- PHP
- Git
- Gulp
- Grunt
- Vue
- Design
- KendoUI
- jQuery/jQueryUI

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/douglasjuliao/

## Site

https://dougjuliao.github.io/

**Comment by carloshenriqueribeiro** [comment]
Olá, tente concluir o nosso desafio
https://github.com/devpartner-br/frontend-test
