### ISSUE TITLE
[São Paulo/SP] Antonio Junior

### ISSUE THREAD

**Issue by antoniojunyor** [frontendbr/me-contrata#31]
## Nome completo

Antonio Balbino da Cunha Junior

## Localidade

São Paulo, SP

## Apresentação

Front-end developer desde 2011, formado em Produção multimídia, fotografo nas horas vagas, durante todo esse tempo trabalhando com desenvolvimento web, aprendi que é importante todo o tipo de produto ou serviço seja de fácil usabilidade para o usuário e que seja rápido, em todas as minha experiências profissionais trabalhei sempre ao lado da equipe de UI/UX, pra entender melhor o usuário e criar algo melhor para o mesmo.

## Outras Informações

No momento estou procurando algo realmente bacana, algo que dure um bom tempo, um lugar sem pré-conceitos ou qualquer tipo de discriminação, e não é fácil achar isso 😅 
Gosto de fazer coisas que vão além do desenvolvimento em si, gosto de participar de definições de layout, gosto de criar coisas novas e interações para o usuário.

## Especialidades

- JavaScript
- Angular (1.x)
- React
- Vue
- Webpack
- GSAP
- Jasmine
- Jest
- HTML
- CSS
- Sass
- UX
- UI

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/antoniojunyor

## Site

http://antoniojunyor.github.io

**Comment by carloshenriqueribeiro** [comment]
Antônio, você tem o perfil que procuramos !
Tente concluir o nosso teste e vamos conversar melhor!
https://github.com/devpartner-br/frontend-test

**Comment by kevenjesus** [comment]
opa @antoniojunyor estou com uma vaga para trabalhar na Faria Lima com React Native tem interesse?
