### ISSUE TITLE
[São Paulo/SP] Lucas Ferreira de Lima

### ISSUE THREAD

**Issue by lucasferreiralimax** [frontendbr/me-contrata#340]
## Nome completo

Lucas Ferreira de Lima

## Localidade

São Paulo - SP - Brasil

## Apresentação

Desenvolvedor Front-end e Designer com 8 anos de experiência
Especialista em criar soluções tecnológicas nos padrões Web
Desenvolvendo sempre soluções com as seguintes tecnologias: CSS, HTML, JavaScript, Webpack, Gulp.js e os Framework Angular e Vue.js

Utilizo o pré-processador Stylus para trabalhar o CSS também trabalho com Less e Sass
Sempre escrevendo o HTML semântico em sua última versão
Utilizando o máximo que a linguagem oferece, utilizo o Pug.js como template.

Meu foco é a melhoria da informação com performance trazendo qualidade e inovação
Criando testes End-to-End usando Cypress.io, gerando resultados positivos nos projetos
Com pesquisas, testes de usabilidade, otimizando a experiência com animações escritas com CSS.

Criei um Web App Open-Source para gerar um simples currículo online ou offline para ajudar as pessoas que precisam de um documento formal sem muita dificuldade
Usando as tecnologias: Vue.js, Firebase hospedando nos servidores Google e Heroku.
Seguindo os padrões PWA (Progressive Web App) e W3C (World Wide Web Consortium)
Link do projeto: [Currículo Grátis](https://curriculo-gratis.web.app)

Desenvolvo minhas habilidades artísticas dentro e fora da tecnologia
Escrevendo poesia e também faço artes visuais (arte urbana)
Criando intervenções nas periferias e vias urbanas
Levando uma mensagem de amor com arte pra quem ama
Buscando novas perspectivas para um mundo melhor toda semana

#### Senac São Paulo
Programador Web
- Junho de 2012 até Julho de 2013

#### CEI - Centro de Ensino Integrado
Informática, Windows, Word, Excel, PowerPoint, Internet, Access e Digitação
- Maio de 2008 até Agosto de 2009

[Trilha de estudos no FreeCodeCamp](https://www.freecodecamp.org/lucasferreiralimax)
[Trilha de estudos no Cursos Alura](https://cursos.alura.com.br/user/lucasferreiralimax)
[Trilha de testes no Pluralsight](https://app.pluralsight.com/profile/lucasferreiralimax)
[Trilha de idiomas no Duolingo](https://www.duolingo.com/profile/ferreiralimax)
[Palestra iBeer - Resource IT & Banco Votorantim](https://ibeer-event.web.app)

- [x] Colaborei no Hacktoberfest 2019 da Digital Ocean e ganhei uma camisa
- [x] Colaborei no Hacktoberfest 2019 da Globo.com e ganhei uma camisa

## Especialidades

- Design (8 anos)
- JavaScript (8 anos)
- HTML (8 anos)
- CSS (8 anos)
- SVG
- ES6
- PWA
- Angular
- Vue.js
- React.js
- Quasar.js
- Nuxt.js
- Typescript
- jQuery
- Gulp
- Grunt
- Webpack
- ParcelJS
- Cypress.io
- Bootstrap
- Material Design
- Bulma.io
- Element.io
- Git
- Atom
- Npm
- Node
- Terminal
- CMD
- Linux
- Windows
- macOS

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

Email: lucasferreiralimax@gmail.com
Celular: 11 982691341
Whatsapp: [Manda um olá se precisar de ajuda, beleza?](https://api.whatsapp.com/send?phone=5511982691341&text=Ol%C3%A1%20Lucas,%20tudo%20bem%20contigo?)

## Site

[Lucas](https://lucas-x.web.app)
[Currículo Grátis](https://curriculo-gratis.web.app)
[CodePen](https://codepen.io/lucaslimax)

**Comment by lucasferreiralimax** [comment]
@felipefialho pode tirar a tag Sênior, não sou ainda não :disappointed:

**Comment by lucasferreiralimax** [comment]
Mas eu sou pleno @felipefialho porque removeu :laughing: :joy: :expressionless:

**Comment by felipefialho** [comment]
Foi mal, to testando label automáticas aqui e ainda não ta muito refinado haha

**Comment by lucasferreiralimax** [comment]
> Foi mal, to testando label automáticas aqui e ainda não ta muito refinado haha

Poderia colocar a flag SP?
