### ISSUE TITLE
[Craíbas/AL - Lucas Ferreira]

### ISSUE THREAD

**Issue by lucasferreiraos** [frontendbr/me-contrata#359]
## Nome completo

Lucas da Silva Ferreira

## Localidade

Craíbas - Alagoas

## Apresentação

Olá, me chamo Lucas e estou à procura da minha primeira oportunidade profissional. Sou graduando em Ciência da Computação pela UFAL. Minha experiência prática ao longo do curso foi com pequenos projetos de software com Django e hoje estudo ciência de dados e aprendizado de máquina com Python para o meu TCC. Em paralelo tenho estudado JavaScript e seus frameworks - Node.js e React. Apesar de ter minhas tecnologias favoritas como toda pessoa programadora tem, eu sempre me coloco à disposição de aprender algo novo que facilite a minha vida na hora de implementar uma solução.

## Outras Informações

Estou à procura da minha primeira oportunidade profissional. Tenho disponibilidade para início imediato em qualquer horário para atuar remotamente. Não tenho disponibilidade para me mudar no momento.

## Especialidades

- Python (3+ anos)
- Django (2 anos)
- JavaScript (1 ano)
- ReactJS (6 meses)
- Node.js (6 meses)
- HTML (1 ano)
- CSS (1 ano)
- Inglês (básico)

## Nível

- Estágio
- Júnior

## Tipo de contratação

- PJ
- CLT

## Tipo de trabalho

- Remoto - Parcial
- Remoto - Total

## Contato

https://linkedin.com/in/lucasferreiraos

**Comment by reichert** [comment]
Lucas, seu telefone?

**Comment by lucasferreiraos** [comment]
> Lucas, seu telefone?

82 9 9695-8264
