### ISSUE TITLE
[Rio Claro/SP] Tarsis de Lima

### ISSUE THREAD

**Issue by tarsislimadev** [frontendbr/me-contrata#412]
## Nome completo
Tarsis Lima

## Localidade
Rio Claro - SP

## Apresentação
Amo o que faço, gosto de novos desafios e sempre busco me atualizar. Gosto de aprender e ensinar o que aprendo para meus colegas de trabalho para que possamos evoluir juntos. Acredito que a boa comunicação e o trabalho em equipe são as chaves para a produtividade e crescimento profissional. Como desenvolvedor full-stack trabalho com a principais tecnologias do mercado React, Angular, Node.js, MongoDB, Docker, Linux e Git.

## Especialidades
* HTML 5
* CSS 3
* JavaScript
* Typescript
* Node.js
* Angular
* SEO
* React
* Redux
* Styled_component
* Nest.js
* Next.js
* Express
* Git (GitHub/GitLab/BitBucket)
* AWS
* Google Cloud
* DevOps
* PostgreSQL
* MongoDB
* Docker
* Kubernetes

## Tempo de experiência
* [ ]  < 1 ano
* [ ]  > 1 ano
* [ ]  > 2 anos
* [x]  > 5 anos
* [ ]  > 10 anos

## Nível
* [x]  Estágio
* [ ]  Júnior
* [x]  Pleno
* [x]  Sênior

## Tipo de contratação
* [x]  CLT
* [ ]  PJ
* [ ]  Freela

## Contato
Linkedin - https://www.linkedin.com/in/tarsislimadev/

## Site
Em desenvolvimento

**Comment by AndreNuernberg** [comment]
Oi @tmvdl ! Como vai?
Você tem interesse em demandas freelancers seguras? 

Na nossa plataforma propomos segurança de em todos os seus processo e também fazemos a mediação, assim você nem se preocupa em buscar clientes! 🤗

Quer conhecer a plataforma da **Vibbra!**?🤓

https://www.vibbra.com.br/vibbrantes/#utm_source=campanha_git

**Comment by brtmvdl** [comment]
I'm in.

**Comment by tarsislimadev** [comment]
Continua disponível
