### ISSUE TITLE
[São Vicente/SP] João Bomfim Junior

### ISSUE THREAD

**Issue by bfmjr** [frontendbr/me-contrata#43]
## Nome completo

João Bomfim Junior

## Localidade

São Vicente, SP

## Apresentação

Desenvolvedor FrontEnd a 4 anos, conhecimentos em HTML/CSS/JS. 
Procuro oportunidades onde envolvam as areas de tecnologia e UX para desenvolvimento e evolução de produtos.

## Outras Informações

Disponel para oportunidade alocado e remoto parcial. Fiz os cursos de UX Weekend e AI & Mobile na Mergo Consultoria.
Fiz uma palestra interna sobre [UX](http://slides.com/bfmjr/ux-introducao). Sempre que possível vou a eventos de tecnologia e assuntos relacionados. Já compareci a eventos como FrontIn nas cidades de São Paulo e Belo Horizonte, na trilha de acessibilidade TDC e no UX Summit.

## Especialidades

- JavaScript
- HTML
- CSS
- WordPress
- UX
- AI

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/bomfimjr

## Site

https://bfmjr.com.br

**Comment by POLLEZI** [comment]
Bom dia! Td joia?
Vc avalia oportunidades em SP?

## Descrição da vaga
_ React
- Desenvolvimento de interfaces
- Experiência em recorte de layouts com Photoshop / InVision
- Javascript - Vanilla e jQuery
- HTML / HTML5 
- CSS3 - SASS / SCSS 
- Consumo de APIs REST
- Git


## Tipo de contratação
CLT

## Local :
Alphaville – SP

## Benefícios
VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Como aplicar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
- enviar no assunto: Vaga REACT front-end
