### ISSUE TITLE
[Rio Claro/SP] Lucas Oliveira

### ISSUE THREAD

**Issue by laobevilaqua** [frontendbr/me-contrata#448]
## Nome completo

Lucas Bevilaqua Araujo de Oliveira

## Localidade

Rio Claro - São Paulo

## Apresentação

Tecnologias me fascinam, amo aprender métodos e tecnologias novas na área de desenvolvimento.

Tenho experiências desenvolvendo sistemas SPAs e já participei do desenvolvimento de aplicações utilizadas por usuários de diversos locais do mundo. Participei de desenvolvimento tanto na parte de back-end quanto front-end, porém tenho mais experiências em front. Para back-end já cheguei a utilizar C#(WebForms, .Net Core e .Net Framework) e Python(Flask) para criação de APIs REST. Em front-end tenho experiências em frameworks e bibliotecas como: React, Angular JS, Angular 2+, Knockout JS e jQuery. Em Banco de dados já trabalhei com: SQL Server e Firebase (real time) 

## Outras Informações

Cursando Faculdade na Fundação Hermínio Ometto (FHO).
Diplomado Técnico de informática pelo Colégio Técnico da Unicamp.

## Especialidades

- JavaScript (2+ anos)
- TypeScript (2+ anos)
- HTML (2+ anos)
- CSS (2+ anos)
- Angular (2+ anos)
- React Native (6 meses)
- Node.js (3 meses)
- SCRUM e KAMBAM (1+ ano)
- Ionic (3 meses)
- Jenkins (2 + anos)
- Git (2+ anos)

## Nível

- Pleno

## Tipo de contratação

- CLT

## Tipo de trabalho

- Remoto - Total

## Contato

https://www.linkedin.com/in/laobevilaqua/

**Comment by samuelfaj** [comment]
@laobevilaqua Ainda está disponível? Me manda um e-mail? comercial@desenvolvimento.ninja

Gostei do seu perfil!
