### ISSUE TITLE
[Nova Lima/MG] Juan Gustavo Marquezine Trindade

### ISSUE THREAD

**Issue by JMarquezine** [frontendbr/me-contrata#51]
## Nome completo

Juan Gustavo Marquezine Trindade

## Localidade

Nova Lima/MG

## Apresentação

Sou formado em Sistemas da Informação na faculdade Promove. Sou desenvolvedor por 5 anos onde o foco principal é backend C#, trabalhando com metodologia ágeis, melhoria do código através de ferramentas, além de execução de testes unitários e algumas noções de DevOps. Tenho também boas noções de linguagens de FrontEnd e estou procurando oportunidades para trabalhar como outras linguagens como ou FullStack.

## Outras Informações

Tenho interesse em vagas home-office ou alocado (Belo Horizonte) com flexibilidade de horário.

## Especialidades

- C#
- JavaScript
- HTML
- CSS
- Jenkins
- Git
- SCRUM
- Kanban
- Docker

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [ ] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/juanmarquezine/

**Comment by pablolopesk8** [comment]
Olá Juan, estamos com uma vaga na Zotto Soluções Mobile para Desenvolvedor Frontend.
Você tem interesse? Pode nos enviar seu currículo por email com seus dados de contato (nome, telefone e email)?

**Comment by POLLEZI** [comment]
Bom dia! Td joia?
Vc avalia oportunidades em SP?

## Descrição da vaga
_ React
- Desenvolvimento de interfaces
- Experiência em recorte de layouts com Photoshop / InVision
- Javascript - Vanilla e jQuery
- HTML / HTML5 
- CSS3 - SASS / SCSS 
- Consumo de APIs REST
- Git


## Tipo de contratação
CLT

## Local :
Alphaville – SP

## Benefícios
VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Como aplicar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
- enviar no assunto: Vaga REACT front-end
