### ISSUE TITLE
[Vitoria/ES] Julian Andrade de Azevedo

### ISSUE THREAD

**Issue by julianchaos** [frontendbr/me-contrata#52]
## Nome completo

Julian Andrade

## Localidade

Vitoria / ES

## Apresentação

Desenvolvedor Web com mais de 10 anos de experiência com conhecimento de diversas linguagens de programação e frameworks. Meus pontos fortes pessoais como desenvolvedor são a rápida capacidade de resolução de problemas, facilidade de aprendizagem de novas tecnologias e facilidade e habilidade em trabalhar em equipe.

As linguagens nas quais tenho proficiência são, principalmente, PHP e Javascript porém já tive oportunidade de trabalhar com C#, Java e Python. Dentre os frameworks com os quais já trabalhei cito AngularJS, Laravel, Slim e .NET. Também tenho experiência com repositórios GIT, métodos agile (principalmente Scrum) e design de sistemas (UML, DDD e MDA). 

## Outras Informações

Meu objetivo é encontrar uma vaga remota em uma empresa que tenha uma cultura e missão que incluam criatividade, inovação e liberdade de ideias e ações e que me proponha desafios. Meus interesses de estudo tem girado em torno da stack MEAN, gerenciamento e boas práticas para equipes remotas e aplicações de métodos agéis.

## Especialidades

- JavaScript (Node.js, Angular, Typescript, npm, Bower, Yarn, etc)
- PHP (Laravel, Slim, Composer, etc)
- .NET (C#)
- CSS (Less, Bootstrap)
- SQL (MySQL, PostgreSQL)
- NoSQL (MongoDB)
- System Design (UML, DDD, MDA)
- Agile (Scrum)

## Nível

- [ ] Estágio
- [ ] Júnior
- [ ] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/juliandeazevedo

## Site

https://github.com/julianchaos

**Comment by julianchaos** [comment]
Fechando a issue após conseguir um trabalho. A empresa viu meu perfil aqui na lista!

**Comment by LFeh** [comment]
Sem palavras mano... Parabéns! 👏👏 👏

**Comment by fdaciuk** [comment]
Sucesso @julianchaos \o/

**Comment by willianjusten** [comment]
Como fico feliz em ver isso! =D

**Comment by viniciusdocanto** [comment]
Que mundo pequeno em, meus parabéns @julianchaos

**Comment by julianchaos** [comment]
Mundo pequeno @viniciusdocanto! Valeu gente, segue o baile!
