### ISSUE TITLE
[Curitiba/PR] Emanuela Coutinho

### ISSUE THREAD

**Issue by ManuCoutinho** [frontendbr/me-contrata#521]
## Nome completo

Emanuela Coutinho

## Localidade

 Curitiba - PR

## Apresentação

Após +10 anos atuando como advogada, estou realizando transição de carreira, em busca minha primeira posição como dev front-end, para que eu possa me tornar uma pixel artist profissional.

## Outras Informações
CSS é arte!

## Especialidades

- JavaScript 
- HTML 
- CSS
- React
- Sass
- Styled Components
- Next.JS
- Bootstrap

## Nível

- Júnior

## Tipo de contratação

- PJ
- CLT
- Freela

## Tipo de trabalho

- Remoto - Parcial
- Remoto - Total
- Alocado

## Contato

[LinkedIn](https://linkedin.com/in/emanuela-coutinho)

## Site

[Porfólio](https://manucoutinho.github.io/)

**Comment by elvislourenco** [comment]
Boa tarde Manu,
Veja nossa oportunidade, se interessar me escreva no e-mail. Abraços
https://github.com/frontendbr/vagas/issues/6296
