### ISSUE TITLE
[Taubaté/SP] Melissa Balsante

### ISSUE THREAD

**Issue by mibsbalsante** [frontendbr/me-contrata#59]
## Nome completo

Melissa Balsante

## Localidade

Taubaté - SP

## Apresentação

Fronteder com 2 anos de experiência. Já passei por diversas ferramentas e acompanho a constante evolução das tecnologias (do site estático com retoques de jQuery, até o build gerado pelo Webpack).

Adoro aprender, ler, botar em prática, compartilhar. Entusiasta open source e functional programming.

## Outras Informações

Disponibilidade para mudança.

## Especialidades

- HTML
- CSS3
- ES6
- Vue.js
- Webpack
- Grunt.js
- Frameworks CSS [Bootstrap, Semantic UI]
- Pré-processadores CSS [SASS, LESS, Stylus]
- Mobile first
- Git

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [ ] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/mibsbalsante

## Site

https://mibsbalsante.github.io

**Comment by alinebastos** [comment]
CSS Wizard <3

**Comment by renanlara** [comment]
Taubaté <3
Cidade linda, gostaria muito de trabalhar aí.

**Comment by mibsbalsante** [comment]
Consegui por outro lugar, tá na hora de fechar aqui. :tada: :tada:
