### ISSUE TITLE
[Salvador/BA] Vitor Britto

### ISSUE THREAD

**Issue by vitorbritto** [frontendbr/me-contrata#67]
## Nome completo

Vitor Hugo Ledo de Lemos Britto

## Localidade

Salvador / BA

## Apresentação

Olá, sou o Vitor Britto. Um Full Stack Developer, apaixonado pelo meu trabalho e que está por trás da [VB Web Studio](http://vbwebstudio.com.br/).

Atualmente me encontro em Salvador - BA, onde desenvolvo projetos para clientes localizados no território nacional e fora dele também.

Descobri o mundo dos códigos há quase duas decádas e mantenho esta mesma paixão desde o primeiro dia dessa descoberta.

Além disso, direciono parte do meu tempo para pesquisas, desenvolvimento de [projetos open-source](https://github.com/vitorbritto) e escrever artigos sobre tecnologia e desenvolvimento web para o meu [blog](http://www.vitorbritto.com.br/blog).

Atuo no mercado desde 2002, elaborando projetos voltados para o posicionamento e fortalecimento da imagem do cliente, através da análise concorrencial e das melhores estratégias, utilizando sempre tecnologias avançadas e ideias inovadoras.

A oportunidade para o sucesso empresarial é única, porém, para atingí-la é preciso ter grande afinidade com etapas e regras a serem rigorosamente cumpridas durante todo o processo de desenvolvimento de um projeto, seja ele de pequeno, médio ou grande porte.

Como profissional em constante atualização de conhecimento, possuidor de extensa bagagem prática e intelectual, percorro fielmente quatro etapas fundamentais para obter sucesso em todos os projetos que desenvolvo: análise e definição de estratégias, criação e interação visual, montagem e refinamento de soluções, e testes de performance e experiência do usuário para que o projeto esteja 100% funcional e correspondendo integralmente às expectativas do cliente. 

## Outras Informações

Tenho disponibilidade para trabalhar de forma remota (total ou parcial, no âmbito de Home-office) para quaisquer regiões e estados ou freelas.

> No momento não tenho disponibilidade para trabalhar alocado.

## Especialidades

Maiores informações a respeito do meu fluxo de trabalho, bem como a Stack de tecnologias e demais ferramentas que utilizo na minha rotina de desenvolvimento podem ser analisados nos links abaixo:

- **Workflow**: https://github.com/vitorbritto/workflow-guide
- **Tech Stack**: https://stackshare.io/vitorbritto/vbwebstudio

### Front-End

- HTML: Pug, EJS
- CSS: Sass, Stylus
- JS: ES6+, jQuery, React, Angular

### Back-End

- NodeJS: Express, SailsJS, Restify
- PHP: WordPress, Laravel, Lúmen, Slim

### Mobile

- React Native
- Ionic

### Databases

- MongoDB
- Redis
- MySQL
- PostgreSQL

### DevOps

- Unix
- AWS
- Docker
- CircleCI
- Travis
- Heroku
- Apache
- NGINX
- Jest
- Mocha (Sinon, Chai)

## Nível

- [ ] Estágio
- [ ] Júnior
- [ ] Pleno
- [x] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

- https://linkedin.com/in/vitorbritto

## Site

- **Portfolio**: http://www.vitorbritto.com.br
- **Github**: https://github.com/vitorbritto

**Comment by renatho** [comment]
Olá Vitor!

Tudo bem?
Estamos buscando dev para montar um time para um fee que temos com um cliente aqui na Grifo. E olhando teu perfil, acreditamos que você possa se encaixar. Os skills principais que estamos buscando é React, Redux e testes com Jest.

Se tiver interesse, gostaríamos de te pedir para se cadastrar em nossa base de parceiros através do link: https://goo.gl/forms/p0eYbZbzVG8NbgOs1
E se você tiver alguns códigos publicados com as skills que buscamos, você pode colocar no campo de Portfólio ;)

Abraços!
