### ISSUE TITLE
[Rio de Janeiro/RJ] Alexander Ribeiro

### ISSUE THREAD

**Issue by alexander2005rj** [frontendbr/me-contrata#70]
## Nome completo

Alexander Ribeiro das Dores

## Localidade

Rio de Janeiro

## Apresentação

Sou analista de testes com mais de 5 anos de experiência. Em paralelo tenho atuado como Analista de Requisitos desde 2009.
Já atuei como desenvolvedor de software durante quase 3 anos utilizando Java e framework SWT. Atualmente estou me atualizando
para unir as três disciplinas (QA, Requisitos e Desenvolvimento) dando um passo em direção à automação de testes utilizando
Ruby, Cucumber, Capybara, Selenium WebDriver e Site Prism.

## Outras Informações

Focando mais na área de testes automatizados. Realizando cursos na área (QA Ninja - Udemy).

## Especialidades

- Análise de requisitos
- Testes funcionais de software
- JavaScript
- HTML
- CSS
- Selenium WebDriver
- Ruby
- Cucumber
- Capybara
- Site Prism

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [ ] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://www.linkedin.com/in/alexander-ribeiro-ctfl-18153a20/

## Site

https://github.com/alexander2005rj

**Comment by POLLEZI** [comment]
Bom dia! Td joia?
Vc avalia oportunidades em SP?

## Descrição da vaga
_ React
- Desenvolvimento de interfaces
- Experiência em recorte de layouts com Photoshop / InVision
- Javascript - Vanilla e jQuery
- HTML / HTML5 
- CSS3 - SASS / SCSS 
- Consumo de APIs REST
- Git


## Tipo de contratação
CLT

## Local :
Alphaville – SP

## Benefícios
VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Como aplicar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
- enviar no assunto: Vaga REACT front-end

**Comment by POLLEZI** [comment]
Bom dia! Td joia?
Vc avalia oportunidades em SP?

## Descrição da vaga
_ React
- Desenvolvimento de interfaces
- Experiência em recorte de layouts com Photoshop / InVision
- Javascript - Vanilla e jQuery
- HTML / HTML5 
- CSS3 - SASS / SCSS 
- Consumo de APIs REST
- Git


## Tipo de contratação
CLT

## Local :
Alphaville – SP

## Benefícios
VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Como aplicar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
- enviar no assunto: Vaga REACT front-end
