### ISSUE TITLE
[Sorocaba/SP] Marcelo Nogueira da Silva

### ISSUE THREAD

**Issue by locemarn** [frontendbr/me-contrata#82]
# Nome Completo:

Marcelo Nogueira da Silva.

## Localidade

Sorocaba/ São Paulo.

## Apresentação

Estudante do 8ºsemestre de engenharia de computação, buscando minha primeira oportunidade profissional na área. Atualmente começando meu TCC, e buscando conhecimentos complementares para agregar no TCC.
Além da faculdade, venho estudando JavaScript e NodeJS. 
Conhecimento em php e Laravel.

## Outras Informações

Sem restrição para mudança ou viagens.

## Especialidades

- HTML
- CSS
- Bootstrap
- JavaScript
- NodeJS
- VueJS
- PHP
- Laravel
- MySQL
- MongoDB
- Firebase
- Linux
- Java

## Nível

- [x] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [ ] Alocado

## Contato

https://www.linkedin.com/in/marcelo-nogueira-408920109/

## Site

https://locemarn.github.io/marcelo-nogueira/

**Comment by locemarn** [comment]
@LFeh tags, please!!

**Comment by sistemaweb** [comment]
Boa tarde, temos uma vaga de Desenvolvedor Web Jr. na Web D7 que acreditamos que te interessará, veja pelo link https://github.com/frontendbr/vagas/issues/1639 e entre em contato pelo email contato@webd7.com
