### ISSUE TITLE
[Floripa - Ilha do Silício / SC] Diogenes Silva

### ISSUE THREAD

**Issue by docbiker** [frontendbr/me-contrata#86]
Tá cansado de fazer cardápio? Acha que tem a manha de codificar para salvar vidas? Quer morar num lugar onde as pessoas tiram férias? Então aqui tem uma oportunidade:

Vaga para dev em startup de saúde premiada em fase de scale-up, com potencial em participação no equity da empresa.

Contratação PJ.

1) DEV (2 vagas)
- Habilidades em desenvolvimento mobile, Swift e/ou Android.
- PHP e acessórios (JS, SQL, JAVA, NODE)

2) DESIGNER (1 vaga)
- Designer para aplicações mobile.

Alocado em Floripa. Não temos interesse em part-time ou trabalho remoto. 

Informações: www.anestech.com.br
(Startup de saúde do ano 2017, vencedora do Shark Tank do Consórcio Brasileiro de Acreditação Hospitalar, selecionada para o Hall da Fama da Pfizer)

Contato: www.linkedin.com/in/diogenes-silva

**Comment by fdaciuk** [comment]
Oi @docbiker! Você está se candidatando ou contratando? Se estiver contratando, poderia fazer o favor de fechar essa issue, e cadastrar a sua oportunidade no nosso repositório de vagas? =)

O endereço é esse: https://github.com/frontendbr/vagas

Muito obrigado =)

**Comment by docbiker** [comment]
Desculpa, enganei-me
