### ISSUE TITLE
[Florianópolis/SC] Bruno Medeiros Costa

### ISSUE THREAD

**Issue by brunomc** [frontendbr/me-contrata#88]
## Nome completo

Bruno Medeiros Costa.

## Localidade

Florianópolis / SC

## Apresentação

Analista / Desenvolvedor de aplicações com JAVA, NodeJS, Angular 5, React
API's, front-end, back-end, Material Design e BootStrap.
Trabalho com os bancos Oracle PL/SQL, PostGreSQL, MySQL e MongoDb.
Experiência de 11 anos com desenvolvimento de sistemas.

## Outras Informações

Tenho disponibilidade para viagens / mudanças

## Especialidades

- JavaScript
- TypeScript
- HTML
- CSS
- PHP
-  JAVA
- NodeJS
- Angular 5
- React

## Nível

- [ ] Estágio
- [ ] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://github.com/brunomc

## Site

https://github.com/brunomc

**Comment by arojunior** [comment]
Fala, @brunomc ! Estamos com uma vaga em aberto aqui na [segware](www.segware.com.br) e acho que o seu perfil se encaixa bem com ela.

A maior parte do nosso backend é em Java, mas também temos algumas coisas em NodeJs.
Nosso front e aplicativos são em react e react-native.

Caso tenha interesse e queira bater um papo, me mande um e-mail: aoliveira@segware.com.br

**Comment by LFeh** [comment]
Rolou?

**Comment by brunomc** [comment]
Fiz o teste da empresa e enviei, porém aguardando resultado da avaliação. Valeu!

**Comment by arojunior** [comment]
Opa! Já avaliei seu teste, juntamente com outro colega do time. Cobrei essa semana se já haviam lhe enviado o feedback, mas as pessoas responsáveis estão viajando. Na segunda eu cobro novamente. Abraço e desculpe a demora.
