### ISSUE TITLE
[Belo Horizonte/MG] Fábio Cícero

### ISSUE THREAD

**Issue by devfabiocicero** [frontendbr/me-contrata#92]
## Nome completo

Fábio Ferreira Cícero Lima.

## Localidade

Belo Horizonte / MG.

## Apresentação

Desenvolvedor Front End desde 2015, com bastante experiência nas tecnologias HTML 5, CSS 3 (Flexbox), JavaScript (ES6+), Framework MVC React JS, Programação OO,  e Controle de Versão Git.

Conhecimento também em Pré-processadores como SASS, Task Runners como Gulp; em Performance na Web; Framework Bootstrap, e Expressões Regulares (Regex).

Além de atuar em uma empresa de tecnologia com o foco voltado para o turismo (Passagens Promo), já atuei também em outros grandes projetos, como BH Harley-Davidson, Líder Aviação e Grupo Embrasil.

Atualmente, focado no desenvolvimento para auxiliar na construção de interfaces ricas com React JS.

## Outras Informações

Alguns cursos concluídos por mim:

- React: Container Components e o ciclo de vida do React
- React: Componentes Reutilizáveis para sua WebApp
- Javascript Avançado: ES6, Orientaçāo a Objetos e Padroēs de Projetos
- Desenvolvedor Javascript

## Especialidades

- JavaScript (ES6+)
- Programação OO
- HTML 5
- CSS 3 (Flexbox)
- React JS
- Git
- SASS

## Nível

- [ ] Estágio
- [x] Júnior
- [x] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [ ] CLT
- [ ] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

https://linkedin.com/in/devfabiocicero

## Site

github.com/devfabiocicero

**Comment by paulo36** [comment]
Ola estou fazendo o curso indicado pela Aline.Porque estou recebendo issues de candidatos?Não tem algo errado

**Comment by alinebastos** [comment]
@paulo36 provavelmente tu tem que mudar a opção lá em cima para Not watching:

![image](https://user-images.githubusercontent.com/387470/38908502-e9088e12-4296-11e8-8cdf-881fd8d8009b.png)

**Comment by LFeh** [comment]
@devfabiocicero rolou contratação? :)

**Comment by devfabiocicero** [comment]
@LFeh rolou sim ;)
