### ISSUE TITLE
sãopaulo/guarulhos

### ISSUE THREAD

**Issue by paulo36** [frontendbr/me-contrata#98]
## Site

ah como faço para não receber curriculos?

**Comment by paulo36** [comment]
Nome completo-paulo josé c pires
Localidadeguarulhos-sp
Apresentação-sou recem formado  desenvolvedor frontend,tenho formação desenvolvedor wordpress
Outras Informações-jornalista,uso o wordpress,magento a nivel básico a algum tempo
Especialidades
Nível-básico  a intermediário
Tipo de contratação-freelancer/remoto
Tipo de trabalho
Contato-paulojosepires@terra.com.br
Site

**Comment by LFeh** [comment]
@paulo36 edita sua primeira mensagem adicionando os campos necessários

**Comment by paulo36** [comment]
ola que campos?

**Comment by paulo36** [comment]
site-http://d2tcomunicacao.com.br/
especialidades-wordpress,magento,frontend

**Comment by renanlara** [comment]
A forma correta seria essa @paulo36 
[Exemplo](https://github.com/frontendbr/me-contrata/issues/35)

**Comment by LFeh** [comment]
@paulo36 Abre outra issue seguindo os padrões :)

**Comment by paulo36** [comment]
ola onde?Não entendi .

**Comment by renanlara** [comment]
@paulo36, leia isso por favor: https://github.com/frontendbr/me-contrata#como-se-cadastrar
